apiVersion: v1
kind: Pod
metadata:
  name: spark-pod-template
spec:
  containers:
  - name: spark-main-container
    volumeMounts:
    - mountPath: /etc/cloudflow-runner-secret
      name: secret-vol
    - mountPath: /mnt/downward-api-volume/
      name: downward-api-volume
    - mountPath: /mnt/spark/storage
      name: default
  volumes:
  - name: secret-vol
    secret:
      defaultMode: 420
      secretName: cdr-generator2
  - name: default
    persistentVolumeClaim:
      claimName: cloudflow-spark
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
        path: metadata.uid
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
        path: metadata.name
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
        path: metadata.namespace
    name: downward-api-volume
