= Introducing Cloudflow Contrib

== Deprecated - The Cloudflow project is deprecated

If you are an existing customer of Lightbend and we have not contacted, please reach out to support. All existing contracts will be honored and assistance with migration to new tools is available.

:description: Cloudflow's community maintained extensions and integrations

:imagesdir: assets/images

== What is Cloudflow Contrib?

Cloudflow Contrib is a Community maintained repository for http://cloudflow.io/[Cloudflow]'s external(Flink & Spark) streaming engine integration.

== Why use Cloudflow Contrib?

Cloudflow Contrib gets Cloudflow's external(Flink & Spark) integrations back in the hands of the users.

The key principles behind this project keeps being:

  - Cloudflow's blueprint is the source of truth of your streamlets interconnections
  - Users are in total control of deploying and managing any Streamlet other than Akka
  - The convenient Streamlet API is preserved for component development

== What's next

Start exploring how to get started with xref:get-started:index.adoc[the Getting started Guide]

**This guide last published: {localdate}**
